version: '3'

services: 
  
  app: 
    container_name: docker-node-mongo
    restart: on-failure
    build: .
    links:
      - mongo
      - nginx
      - certbot
  mongo:
    container_name: mongo
    image: mongo
    ports: 
      - '27017:27017'
  nginx:
    container_name: webserver
    image: nginx:mainline-alpine
    restart: unless-stopped
    ports: 
     - '80:80'
    volumes:
      - ./public:/var/www/html
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/etc:/etc/letsencrypt
      - ./data/certbot/var:/var/lib/letsencrypt
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/lib/letsencrypt
      - ./public:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email hackleman.jason@gmail.com --agree-tos --no-eff-email --staging -d taxidata.tk  -d www.taxidata.tk
