version: '3'

services: 
  app: 
    container_name: docker-node-mongo
    restart: on-failure
    build: .
    ports: 
     - '80:4000'
     - '8001:8001'
    links:
     - mongo
     - oracle-xe
  mongo:
    container_name: mongo
    image: mongo
    ports: 
     - '27017:27017'
  oracle-xe:
    container_name: oracle-xe
    image: hackleman/oracleproject
    ports:
      - '32118:1521'
      - '35518:5500'
    volumes:
      - ./data:/opt/oracle/oradata
    environment:
      - ORACLE_PWD=Oracle18